spring:
  kafka:
    admin:
      properties:
        connections.max.idle.ms: 10000
        request.timeout.ms: 10000
        metrics.recording.level: DEBUG
        retries: 10
      fail-fast: true
      client-id: TRANSFORMER-APP
    bootstrap-servers: localhost:9092


  cloud:
    function:
      definition: processTransfer;processBalanceLeg1;processBalanceLeg2
    stream:
      bindings:
        processTransfer-in-0:
          destination: funds.transformer.request
        processTransfer-out-0:
          destination: funds.transfer.request


        processBalanceLeg1-in-0:
          destination: balance.transformer.request
        processBalanceLeg1-out-0:
          destination: balance.update.request


        processBalanceLeg2-in-0:
          destination: balance.update.response
        processBalanceLeg2-out-0:
          destination: balance.transformer.response



      kafka:
        streams:
          binder:
            configuration:
              commit.interval.ms: 1000

server:
  port: 7081




