spring:
  config:
    activate:
      on-profile: avro
  cloud:
    function:
      definition: processTransfer;processBalanceLeg1;processBalanceLeg2
    stream:
      kafka:
        streams:
          binder:
            functions:
              processTransfer:
                applicationId: transformerApp-processTransfer
                groupId: transformer
              processBalanceLeg1:
                applicationId: transformerApp-processBalanceL1
                groupId: transformer
              processBalanceLeg2:
                applicationId: transformerApp-processBalanceL2
                groupId: transformer
            brokers: localhost:9092
            configuration:
              default.value.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
              default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              auto.create.topics: false
              schema.registry.url: "http://127.0.0.1:8081"
              specific.avro.reader: true
            deserialization-exception-handler: logandcontinue

      bindings:
        processTransfer-in-0:
          destination: funds.transformer.request
        processTransfer-out-0:
          destination: funds.transfer.request
        processBalanceLeg1-in-0:
          destination: balance.transformer.request
        processBalanceLeg1-out-0:
          destination: balance.update.request
        processBalanceLeg2-in-0:
          destination: balance.update.response
        processBalanceLeg2-out-0:
          destination: balance.transformer.response

logging:
  level:
    web: debug


server:
  port: 7081




