spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: restTest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    properties:
      schema.registry.url: http://${schema-endpoint}
      specific.avro.reader: true


server:
  port: 8080

banking:
  partitions: 1
  replicas: 1

router-endpoint: localhost:7082
elastic-endpoint: localhost:9200
schema-endpoint: http://127.0.0.1:8081




#properties:
#      schema.registry.url: ${SCHEMA_REGISTRY_ENDPOINT}
