language: java
dist: trusty
jdk:
  - openjdk8
branches:
  only:
    - master
env:
  global:
    - CODECOV_TOKEN='8a4f3c3f-7201-4560-8a79-df05489d8166'

after_success:
  - bash <(curl -s https://codecov.io/bash)
