coverage:
  status:
    project:
      default:
        target: auto
        threshold: 10%
        paths:
          - "src"
        branches:
          - master
        if_ci_failed: error
        informational: true

