version: '3'
services:
  rest:
    image: rest:latest
    container_name: rest
    build:
      context: rest
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    environment:
      - ROUTER-ENDPOINT=router-streams:7082
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=host.docker.internal:19092



  transformer-streams:
    image: transformer-streams:latest
    container_name: transformer-streams
    build:
      context: transformer-streams
      dockerfile: Dockerfile
    depends_on:
      - rest
    environment:
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=host.docker.internal:19092
      - SERVER_PORT=7081



  router-streams:
    image: router-streams:latest
    container_name: router-streams
    ports:
      - "7082:7082"
    build:
      context: router-streams
      dockerfile: Dockerfile
    depends_on:
      - rest
    environment:
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=host.docker.internal:19092
      - SERVER_PORT=7082


  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=BANK
    volumes:
      - ./bin/bank/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./bin/bank/data.sql:/docker-entrypoint-initdb.d/2-data.sql
      - /var/lib/postgresql/data



  persistence:
    image: persistence:latest
    container_name: persistence
    build:
      context: persistence
      dockerfile: Dockerfile
    ports:
      - "7083:7083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/BANK
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
      - SERVER_PORT=7083
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=host.docker.internal:19092
    depends_on:
      - db






  dbTwo:
    image: postgres
    container_name: dbTwo
    ports:
      - "5442:5442"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=BANK2
    volumes:
      - ./bin/bank2/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./bin/bank2/data.sql:/docker-entrypoint-initdb.d/2-data.sql
      - /var/lib/postgresql/dataTwo



  persistence2:
    image: persistence:latest
    container_name: persistence2
    environment:
      - SPRING_PROFILES_ACTIVE=persistence2
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbTwo:5432/BANK2
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=host.docker.internal:19092
    ports:
      - "8084:8084"
    build:
      context: persistence
      dockerfile: Dockerfile
    depends_on:
      - dbTwo


