spring:
  kafka:
    bootstrap-servers: localhost:9092
    admin:
      client-id: ROUTING-APP

  cloud:
    stream:
      function:
        definition: consumeInitialTransfer;validationConsumer;upsertMetric;balanceRequestConsumer
#        ;supplyTransferStatus

      bindings:
        upsertMetric-in-0:
          destination: funds.transfer.status
        upsertMetric-out-0:
          destination: transfer.status

        consumeInitialTransfer-in-0:
          destination: funds.transfer.request

        validationConsumer-in-0:
          destination: router.validate.transfer

        balanceRequestConsumer-in-0:
          destination: balance.update.request






      kafka:
        streams:
          binder:
            configuration:
              default:
                key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              commit.interval.ms: 1000
            auto-create-topics: true




        bindings:
          upsertMetric-in-0:
            keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
          consumeInitialTransfer-in-0:
            enableDlq: true
            dlqName: funds.transfer.error















server:
  port: 8082


logging:
  level: debug
