spring:
  kafka:
    bootstrap-servers: localhost:9092

  cloud:
    stream:
      function:
        definition: consumeInitialTransfer;validationConsumer;upsertMetric;balanceRequestConsumer


      bindings:
        upsertMetric-in-0:
          destination: funds.transfer.status
        upsertMetric-out-0:
          destination: transfer.status

        consumeInitialTransfer-in-0:
          destination: funds.transfer.request

        validationConsumer-in-0:
          destination: router.validate.transfer

        balanceRequestConsumer-in-0:
          destination: balance.update.request





      kafka:
        streams:
          binder:
            configuration:
              default:
                key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              commit.interval.ms: 1000
            min-partition-count: 1
            application-id: ROUTING-APP
            deserialization-exception-handler: logandcontinue





        bindings:
          upsertMetric-in-0:
            keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde

          consumeInitialTransfer-in-0:
            enableDlq: true
            dlqName: funds.transfer.error








server:
  port: 8082


logging:
  level: debug
